# Generated by Django 3.0.1 on 2020-01-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_handyhelper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posted_by', to='app_handyhelper.User')),
                ('saved_jobs', models.ManyToManyField(related_name='user_saved_jobs', to='app_handyhelper.User')),
            ],
        ),
    ]
